name: First CI Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Show files
        run: ls -la

      - name: Test Runner
        run: echo "CI Pipeline Working!"
